import * as fs from 'fs';
import * as path from 'path';

export interface AgentStateData {
  last_seen_post_id?: string;
  processed_post_ids: string[];
  agent_generated_post_ids: string[];
}

export interface StateManagerOptions {
  filePath?: string;
  maxStoredIds?: number;
}

export class AgentStateManager {
  private filePath: string;
  private maxStoredIds: number;
  private state: AgentStateData;

  constructor(options?: StateManagerOptions) {
    this.filePath = options?.filePath
      ? path.resolve(process.cwd(), options.filePath)
      : path.resolve(process.cwd(), './data/agent-state.json');
    this.maxStoredIds = options?.maxStoredIds || 1000;
    this.state = {
      processed_post_ids: [],
      agent_generated_post_ids: [],
    };
    this.load();
  }

  /**
   * Loads state from the local JSON file.
   */
  public load(): AgentStateData {
    try {
      if (fs.existsSync(this.filePath)) {
        const raw = fs.readFileSync(this.filePath, 'utf-8');
        const parsed = JSON.parse(raw);
        this.state = {
          last_seen_post_id: typeof parsed.last_seen_post_id === 'string' ? parsed.last_seen_post_id : undefined,
          processed_post_ids: Array.isArray(parsed.processed_post_ids) ? parsed.processed_post_ids : [],
          agent_generated_post_ids: Array.isArray(parsed.agent_generated_post_ids) ? parsed.agent_generated_post_ids : [],
        };
      }
    } catch {
      // If file is corrupted or unreadable, initialize clean state
      this.state = {
        processed_post_ids: [],
        agent_generated_post_ids: [],
      };
    }
    return this.getState();
  }

  /**
   * Saves state to disk. Ensures parent directory exists.
   */
  public save(): void {
    try {
      const dir = path.dirname(this.filePath);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }

      // Trim arrays to prevent unbounded growth
      if (this.state.processed_post_ids.length > this.maxStoredIds) {
        this.state.processed_post_ids = this.state.processed_post_ids.slice(-this.maxStoredIds);
      }
      if (this.state.agent_generated_post_ids.length > this.maxStoredIds) {
        this.state.agent_generated_post_ids = this.state.agent_generated_post_ids.slice(-this.maxStoredIds);
      }

      fs.writeFileSync(this.filePath, JSON.stringify(this.state, null, 2), 'utf-8');
    } catch (err) {
      console.error(`[ERROR] Failed to save agent state to ${this.filePath}:`, err);
    }
  }

  /**
   * Returns a copy of the current state.
   */
  public getState(): AgentStateData {
    return {
      last_seen_post_id: this.state.last_seen_post_id,
      processed_post_ids: [...this.state.processed_post_ids],
      agent_generated_post_ids: [...this.state.agent_generated_post_ids],
    };
  }

  /**
   * Checks if a post ID has already been processed by the agent.
   */
  public isProcessed(postId: string): boolean {
    if (!postId) return false;
    return this.state.processed_post_ids.includes(postId);
  }

  /**
   * Checks if a post ID was generated by the agent itself.
   * Used to prevent infinite agent self-loops.
   */
  public isAgentGenerated(postId: string): boolean {
    if (!postId) return false;
    return this.state.agent_generated_post_ids.includes(postId);
  }

  /**
   * Marks a post ID as processed.
   */
  public markProcessed(postId: string): void {
    if (!postId || this.state.processed_post_ids.includes(postId)) return;
    this.state.processed_post_ids.push(postId);
    this.save();
  }

  /**
   * Records a post ID generated by the agent.
   */
  public recordAgentGenerated(postId: string): void {
    if (!postId || this.state.agent_generated_post_ids.includes(postId)) return;
    this.state.agent_generated_post_ids.push(postId);
    // Also mark as processed
    if (!this.state.processed_post_ids.includes(postId)) {
      this.state.processed_post_ids.push(postId);
    }
    this.save();
  }

  /**
   * Updates the last seen post ID cursor.
   */
  public setLastSeenPostId(postId: string): void {
    this.state.last_seen_post_id = postId;
    this.save();
  }

  /**
   * Clears state in memory and deletes state file if requested.
   */
  public clear(deleteFile = false): void {
    this.state = {
      processed_post_ids: [],
      agent_generated_post_ids: [],
    };
    if (deleteFile && fs.existsSync(this.filePath)) {
      try {
        fs.unlinkSync(this.filePath);
      } catch {}
    } else {
      this.save();
    }
  }
}
