import { MattermostClient, MattermostPost, MattermostUser } from './client';
import { hasMention, extractInstruction } from './mentions';
import { AgentStateManager } from '../state/state-manager';
import { AIProvider, ThreadContextMessage } from '../ai/provider';

export interface ListenerOptions {
  client: MattermostClient;
  stateManager: AgentStateManager;
  aiProvider: AIProvider;
  username: string;
  pollIntervalSeconds?: number;
  channels?: string[]; // Optional: restrict polling to specific channel IDs or names
  maxThreadContext?: number;
}

export class MattermostAgentListener {
  private client: MattermostClient;
  private stateManager: AgentStateManager;
  private aiProvider: AIProvider;
  private username: string;
  private pollIntervalMs: number;
  private targetChannels?: string[];
  private maxThreadContext: number;

  private pollTimer: NodeJS.Timeout | null = null;
  private isPolling = false;
  private currentUser: MattermostUser | null = null;

  constructor(options: ListenerOptions) {
    this.client = options.client;
    this.stateManager = options.stateManager;
    this.aiProvider = options.aiProvider;
    this.username = options.username.replace(/^@/, '').toLowerCase().trim();
    this.pollIntervalMs = (options.pollIntervalSeconds || 5) * 1000;
    this.targetChannels = options.channels;
    this.maxThreadContext = options.maxThreadContext || 10;
  }

  /**
   * Initializes the listener by verifying authentication with Mattermost.
   */
  public async initialize(): Promise<MattermostUser> {
    try {
      this.currentUser = await this.client.getMe();
      console.log(`[INFO] Authenticated as @${this.currentUser.username} (${this.currentUser.id})`);
      return this.currentUser;
    } catch (err: any) {
      console.error(`[ERROR] Mattermost authentication failed: ${err.message}`);
      throw err;
    }
  }

  /**
   * Starts the polling loop.
   */
  public async start(): Promise<void> {
    if (!this.currentUser) {
      await this.initialize();
    }

    console.log(`[INFO] Polling started (interval: ${this.pollIntervalMs / 1000}s, trigger: @${this.username})`);
    // Run first tick immediately
    await this.pollOnce();

    // Start background interval
    this.pollTimer = setInterval(async () => {
      await this.pollOnce();
    }, this.pollIntervalMs);
  }

  /**
   * Stops the polling loop.
   */
  public stop(): void {
    if (this.pollTimer) {
      clearInterval(this.pollTimer);
      this.pollTimer = null;
    }
    console.log('[INFO] Polling stopped');
  }

  /**
   * Executes a single polling cycle.
   * Scans accessible channels for mentions and dispatches responses.
   */
  public async pollOnce(): Promise<number> {
    if (this.isPolling) return 0;
    this.isPolling = true;

    let processedCount = 0;

    try {
      // 1. Get accessible channels
      const channels = await this.client.getMyChannels();
      const channelsToPoll = this.targetChannels && this.targetChannels.length > 0
        ? channels.filter((c) => this.targetChannels!.includes(c.id) || this.targetChannels!.includes(c.name))
        : channels;

      // 2. Poll posts for each channel
      for (const channel of channelsToPoll) {
        try {
          const postsResponse = await this.client.getChannelPosts(channel.id, { perPage: 20 });
          if (!postsResponse || !postsResponse.order || postsResponse.order.length === 0) {
            continue;
          }

          // Order from oldest to newest for chronological processing
          const postIds = [...postsResponse.order].reverse();

          for (const postId of postIds) {
            const post = postsResponse.posts[postId];
            if (!post) continue;

            const handled = await this.handlePost(post);
            if (handled) {
              processedCount++;
            }
          }
        } catch (channelErr: any) {
          console.error(`[ERROR] Failed to fetch posts for channel ${channel.name || channel.id}: ${channelErr.message}`);
        }
      }
    } catch (err: any) {
      console.error(`[ERROR] Mattermost polling cycle failed: ${err.message}`);
    } finally {
      this.isPolling = false;
    }

    return processedCount;
  }

  /**
   * Evaluates and processes a single Mattermost post.
   * Returns true if the post triggered an AI response.
   */
  public async handlePost(post: MattermostPost): Promise<boolean> {
    if (!post || !post.id) return false;

    // 1. CRITICAL: Ignore posts generated by the agent itself (Prevents infinite self-loops)
    if (this.stateManager.isAgentGenerated(post.id)) {
      // Log only on first encounter
      if (!this.stateManager.isProcessed(post.id)) {
        console.log(`[INFO] Ignoring agent-generated post: ${post.id}`);
        this.stateManager.markProcessed(post.id);
      }
      return false;
    }

    // 2. Ignore already processed posts (Deduplication)
    if (this.stateManager.isProcessed(post.id)) {
      return false;
    }

    // 3. Ignore deleted or system message posts
    if (post.delete_at && post.delete_at > 0) {
      this.stateManager.markProcessed(post.id);
      return false;
    }

    // 4. Check for @username mention
    if (!hasMention(post.message, this.username)) {
      // Mark as seen/processed to avoid re-evaluating in future cycles
      this.stateManager.markProcessed(post.id);
      return false;
    }

    // --- MENTION DETECTED ---
    // NOTE: Self-triggering is intentionally supported!
    // A post created by the human user (post.user_id === this.currentUser?.id) WILL proceed here.
    console.log(`[INFO] Mention detected in post: ${post.id} (Channel: ${post.channel_id})`);
    console.log(`[INFO] Processing post: ${post.id}`);

    // Mark as processed early to prevent concurrent processing
    this.stateManager.markProcessed(post.id);
    this.stateManager.setLastSeenPostId(post.id);

    // 5. Extract instruction prompt
    const instruction = extractInstruction(post.message, this.username);
    const prompt = instruction || 'Hello, how can I assist you?';

    // 6. Retrieve thread context if message is part of a thread
    let threadContext: ThreadContextMessage[] = [];
    if (post.root_id) {
      try {
        const threadResp = await this.client.getPostThread(post.root_id);
        if (threadResp && threadResp.order && threadResp.order.length > 0) {
          // Sort thread posts chronologically
          const threadPosts = threadResp.order
            .map((id) => threadResp.posts[id])
            .filter((p): p is MattermostPost => Boolean(p && p.id !== post.id && (!p.delete_at || p.delete_at === 0)))
            .slice(-this.maxThreadContext); // Limit to recent window

          threadContext = threadPosts.map((p) => ({
            author: p.user_id === this.currentUser?.id ? `@${this.username}` : `user_${p.user_id.slice(0, 6)}`,
            message: p.message,
            timestamp: p.create_at,
          }));
        }
      } catch (threadErr: any) {
        console.error(`[ERROR] Failed to fetch thread context for ${post.root_id}: ${threadErr.message}`);
      }
    }

    // 7. Generate AI Response
    console.log('[INFO] Generating AI response');
    let aiResponseText: string;

    try {
      aiResponseText = await this.aiProvider.generate(prompt, threadContext);
    } catch (aiErr: any) {
      console.error(`[ERROR] AI provider request failed: ${aiErr.message}`);
      aiResponseText = 'Unable to process this request right now.';
    }

    // 8. Post response to Mattermost
    // Preserve thread relationship: if root message, reply to post.id; if thread message, reply to post.root_id.
    const targetRootId = post.root_id || post.id;

    try {
      const createdPost = await this.client.createPost({
        channel_id: post.channel_id,
        message: aiResponseText,
        root_id: targetRootId,
      });

      // 9. CRITICAL: Record created post ID in agent_generated_post_ids
      this.stateManager.recordAgentGenerated(createdPost.id);
      console.log(`[INFO] Response posted: ${createdPost.id}`);
      return true;
    } catch (postErr: any) {
      console.error(`[ERROR] Failed to post AI response to Mattermost: ${postErr.message}`);
      return false;
    }
  }
}
